# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('cf_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ton_balance', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('not_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('referral_code', models.CharField(default=users.models.generate_referral_code, max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('auto_water_until', models.DateTimeField(blank=True, null=True)),
                ('staking_cf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('staking_until', models.DateTimeField(blank=True, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.user')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
