# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CF', 'CF Tree'), ('TON', 'TON Tree'), ('NOT', 'NOT Tree')], max_length=3)),
                ('level', models.IntegerField(default=1)),
                ('income_per_hour', models.FloatField(default=1.0)),
                ('branches_collected', models.IntegerField(default=0)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('fertilized_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='users.user')),
            ],
            options={
                'verbose_name': 'Дерево',
                'verbose_name_plural': 'Деревья',
                'unique_together': {('user', 'type')},
            },
        ),
    ]
