# Generated by Django 5.2.1 on 2025-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('CF', 'CF Tree'), ('TON', 'TON Tree')], max_length=3),
        ),
    ]
