# Generated by Django 5.2.1 on 2025-06-10 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('duration_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tree',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tree',
            name='auto_water_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='branches_collected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='income_per_hour',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tree',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('CF', 'FLORA'), ('TON', 'TON-Дерево')], default='CF', max_length=20),
        ),
    ]
