# Generated by Django 5.2.2 on 2025-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='auto_water_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
