# Generated by Django 5.2.1 on 2025-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TON-раздача',
                'verbose_name_plural': 'TON-раздачи',
            },
        ),
    ]
