# Generated by Django 5.2.1 on 2025-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tondistribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tondistribution',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='duration_hours',
            field=models.PositiveIntegerField(default=24, help_text='На какой период (в часах) действует раздача (необязательно, просто для информации).'),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если True, можно выполнить распределение TON через админ-экшен. После распределения будет установлено False.'),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, help_text='Общее количество TON, которое будет раздано поровну.', max_digits=20),
        ),
    ]
