# Generated by Django 5.2.1 on 2025-06-02 19:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_rename_start_time_tondistribution_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tondistribution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tree',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='duration_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='branches_collected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='income_per_hour',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tree',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('CF', 'CryptoFarm'), ('TON', 'TON-Дерево')], default='CF', max_length=3),
        ),
    ]
