# Generated by Django 5.2.1 on 2025-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_tondistribution_options_alter_tree_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('CF', 'CryptoFarm'), ('TON', 'TON-Дерево')], default='CF', max_length=20),
        ),
    ]
