# Generated by Django 5.2.1 on 2025-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_tree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='auto_water_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
