# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Тип')),
                ('token_type', models.CharField(choices=[('CF', 'CF Token'), ('TON', 'TON Token'), ('NOT', 'NOT Token')], max_length=3, verbose_name='Тип токена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Цена за единицу')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('expired', 'Истек')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Цена за единицу')),
                ('token_type', models.CharField(choices=[('CF', 'CF Token'), ('TON', 'TON Token'), ('NOT', 'NOT Token')], max_length=3, verbose_name='Тип токена')),
                ('commission', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Комиссия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases', to='users.user', verbose_name='Покупатель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='p2p.order', verbose_name='Ордер')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales', to='users.user', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
