# Generated by Django 5.1.1 on 2025-06-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15, verbose_name='Минимальная сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Платежные реквизиты'),
        ),
    ]
