# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('auto_water', 'Авто-полив'), ('fertilizer', 'Удобрение'), ('ton_tree', 'Дерево TON'), ('not_tree', 'Дерево NOT'), ('cf_slot', 'CF Слот')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_token_type', models.CharField(default='CF', max_length=3, verbose_name='Тип токена для оплаты')),
                ('duration', models.IntegerField(blank=True, help_text='Длительность в часах', null=True, verbose_name='Длительность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('image', models.CharField(blank=True, help_text='URL изображения или иконки', max_length=255, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.user', verbose_name='Пользователь')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.shopitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
