# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('token_type', models.CharField(default='CF', max_length=3, verbose_name='Тип токена')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма вознаграждения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('claimed', 'Получен')], default='active', max_length=10, verbose_name='Статус')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('claimed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakings', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стейкинг',
                'verbose_name_plural': 'Стейкинги',
                'ordering': ['-start_date'],
            },
        ),
    ]
