# Generated by Django 5.1.1 on 2025-06-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('watering', 'Полив'), ('auto_water', 'Авто-полив'), ('order', 'Ордер'), ('staking', 'Стейкинг'), ('referral', 'Реферал'), ('system', 'Системное')], max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_notifications', models.BooleanField(default=True, verbose_name='Уведомления о поливе')),
                ('auto_water_notifications', models.BooleanField(default=True, verbose_name='Уведомления об авто-поливе')),
                ('order_notifications', models.BooleanField(default=True, verbose_name='Уведомления об ордерах')),
                ('staking_notifications', models.BooleanField(default=True, verbose_name='Уведомления о стейкинге')),
                ('referral_notifications', models.BooleanField(default=True, verbose_name='Уведомления о рефералах')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('telegram_notifications', models.BooleanField(default=True, verbose_name='Уведомления через Telegram')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Уведомления по Email')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
